// SPDX-License-Identifier: GPL-3.0-only

/** Historical settings defaults; aliases and hydration omissions are intentionally preserved. */
export const defaults = {
  SPONSORED: true,
  NF_TABLIST_STORIES_REELS_ROOMS: false,
  NF_STORIES: false,
  NF_SURVEY: true,
  NF_PEOPLE_YOU_MAY_KNOW: false,
  NF_PAID_PARTNERSHIP: true,
  NF_SPONSORED_PAID: true,
  NF_SUGGESTIONS: true,
  NF_FOLLOW: true,
  NF_PARTICIPATE: true,
  NF_REELS_SHORT_VIDEOS: false,
  NF_SHORT_REEL_VIDEO: false,
  NF_META_AI: true,
  NF_META_AI_PROMPTS: true,
  NF_AI_INFO_POSTS: false,
  NF_EVENTS_YOU_MAY_LIKE: true,
  NF_ANIMATED_GIFS_POSTS: false,
  NF_ANIMATED_GIFS_PAUSE: false,
  NF_SHARES: false,
  NF_LIKES_MAXIMUM: false,
  NF_TOP_CARDS_PAGES: false,
  NF_HIDE_VERIFIED_BADGE: false,
  NF_FILTER_VERIFIED_BADGE: false,
  NF_AI_SIDE_PANELS: false,
  GF_PAID_PARTNERSHIP: true,
  GF_SUGGESTIONS: false,
  GF_SHORT_REEL_VIDEO: false,
  GF_ANIMATED_GIFS_POSTS: false,
  GF_ANIMATED_GIFS_PAUSE: false,
  GF_SHARES: false,
  VF_LIVE: false,
  VF_INSTAGRAM: false,
  VF_DUPLICATE_VIDEOS: false,
  VF_ANIMATED_GIFS_PAUSE: false,
  PP_ANIMATED_GIFS_POSTS: false,
  PP_ANIMATED_GIFS_PAUSE: false,
  NF_BLOCKED_FEED: ["1", "0", "0"],
  GF_BLOCKED_FEED: ["0", "1", "0"],
  VF_BLOCKED_FEED: ["0", "0", "1"],
  MP_BLOCKED_FEED: ["1", "0", "0"],
  PP_BLOCKED_FEED: ["1", "0", "0"],
  OTHER_INFO_BOX_CORONAVIRUS: false,
  OTHER_INFO_BOX_CLIMATE_SCIENCE: false,
  OTHER_INFO_BOX_SUBSCRIBE: false,
  REELS_CONTROLS: true,
  REELS_DISABLE_LOOPING: true,
  NF_BLOCKED_ENABLED: false,
  GF_BLOCKED_ENABLED: false,
  VF_BLOCKED_ENABLED: false,
  MP_BLOCKED_ENABLED: false,
  PP_BLOCKED_ENABLED: false,
  NF_BLOCKED_RE: false,
  GF_BLOCKED_RE: false,
  VF_BLOCKED_RE: false,
  MP_BLOCKED_RE: false,
  PP_BLOCKED_RE: false,
  DLG_VERBOSITY: "0",
  VERBOSITY_DEBUG: false,
  VERBOSITY_MESSAGE_BG_COLOUR: "LightGrey",
  CMF_BTN_OPTION: "1",
  CMF_DIALOG_OPTION: "0",
  CMF_BORDER_COLOUR: "OrangeRed",
};

/** Exact default-key contract, independent of localized labels or DOM code. */
export type OptionDefaults = typeof defaults;
