const SEPARATOR = "İİ";

function createState() {
  return {
    SEP: SEPARATOR,
    scanCountStart: 0,
    scanCountMaxLoop: 15,
    noChangeCounter: 0,
    options: {},
    optionsReady: false,
    language: "",
    filters: {},
    hideAnInfoBox: false,
    dictionarySponsored: [],
    dictionaryReelsAndShortVideos: [],
    dictionaryFollow: [],
    isNF: false,
    isGF: false,
    isVF: false,
    isMF: false,
    isAF: false,
    isSF: false,
    isRF: false,
    isPP: false,
    isRF_InTimeoutMode: false,
    gfType: "",
    vfType: "",
    mpType: "",
    prevURL: "",
    prevPathname: "",
    prevQuery: "",
    echoEl: null,
    echoElFirstNote: null,
    echoElCreatedCount: 0,
    echoELFirstPost: null,
    echoCount: 0,
    echoCPID: "",
    isDarkMode: null,
    cssID: "",
    cssOID: "",
    tempStyleSheetCode: "",
    hideAtt: "",
    showAtt: "",
    hideWithNoCaptionAtt: "",
    cssHideEl: "",
    cssEcho: "",
    cssHideNumberOfShares: "",
    btnToggleEl: null,
    iconClose: "",
    iconToggleHTML: "",
    iconDialogHeaderHTML: "",
    iconDialogSearchHTML: "",
    iconDialogFooterHTML: "",
    iconLegendHTML: "",
    dialogSectionIcons: {},
    dialogFooterIcons: {},
    iconNewWindow: "",
    iconNewWindowClass: "cmf-link-new",
    isChromium: false,
  };
}

module.exports = {
  SEPARATOR,
  createState,
};
